//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class coas
    {
        public Nullable<int> Request_ID { get; set; }
        public string COA_ID { get; set; }
        public string Product_Name { get; set; }
        public string Pre_existing_COA_ID { get; set; }
        public string License_Type { get; set; }
        public string PK { get; set; }
        public string PDF_language { get; set; }
        public string Recipient_Organization_Name { get; set; }
        public string Recipient_City { get; set; }
        public string Recipient_Country___Region { get; set; }
        public string Recipient_Type { get; set; }
        public string location { get; set; }
        public int row_id { get; set; }
    }
}
