//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class discovery
    {
        public int ictag { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string serial { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string cpu { get; set; }
        public string hdd { get; set; }
        public string ram { get; set; }
        public string optical_drive { get; set; }
        public string location { get; set; }
        public string has_SSD { get; set; }
    }
}
