//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class label_log
    {
        public string Time { get; set; }
        public string serial { get; set; }
        public int ictags { get; set; }
        public string pallet { get; set; }
        public string refurbisher { get; set; }
        public string Manu { get; set; }
        public string Model { get; set; }
        public string pre_coa { get; set; }
    }
}
