//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class magento_sku_brand
    {
        public string name { get; set; }
        public string dropdown_value { get; set; }
        public string sku_name { get; set; }
        public int index { get; set; }
    }
}
