//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class magento_html
    {
        public int id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string drop_down_value { get; set; }
        public string html { get; set; }
    }
}
