//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitor_log
    {
        public Nullable<System.DateTime> time { get; set; }
        public int ictag { get; set; }
        public string manu { get; set; }
        public string monitor_ID { get; set; }
        public string serial { get; set; }
        public Nullable<int> size { get; set; }
        public string resou { get; set; }
        public string model { get; set; }
    }
}
