//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_log
    {
        public System.DateTime time { get; set; }
        public string ictags { get; set; }
        public string wcoa { get; set; }
        public string ocoa { get; set; }
        public string Manufacture { get; set; }
        public string Model { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string HDD { get; set; }
        public string serial { get; set; }
        public string channel { get; set; }
        public string pre_coa { get; set; }
        public string location { get; set; }
        public string video_card { get; set; }
        public string screen_size { get; set; }
        public string bin_location { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> assign_time { get; set; }
    }
}
